language: cpp
compiler:
  - gcc
cache: apt
before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously
install:
  - sudo apt-get -yq install build-essential
script:
  - make   #< Build